'''
Template RPS script. Feel free to write everything from scratch, but if you do
use this, all you need to edit is the rps_strategy function
'''

import random as r

from bot_helper import *

_TEAM_NAME = "EthanBot"  # Note: change this to your team's name

################################################################################

data = 'SSRPSSSSPRSSRPPPPRRSSRSSRSRPPRSRRPPSSRRPRPSRSPRSSSPRPRSRRSRRPRSSPSSPPRSPSPSSPPPRPRRPSPRSPSRRSPRPPPSSPPRRSRRRSPSPPRPPRSRSPRRPSPRPPSRPPRRPSRPSRRPPSSPSPPRSPPRRPPSRRSSPPSPRSRRSSPPRPRRRSPSRRSSRPPRSRSSRRRPSSRSPSPSSPRSSRPRRRRSSRPSRSPSRRSSPSRPSSRSRRPPRRRPPPRSPSPSSPPSSRRRRSRRRRRPSRRRSRSRPRSRSSRPRSPPPRRPSSRPRSRPSSPPPPRRPPSPRRRPSRPSSRPPSPPPPSPPRPSRSRRSPSSSPSRPPRRPPSPPSRRRPRRRSSPPSRSSPRSPSPPSRSSSPRRPRSSSSPPPRPRRRPRRPRSRRRPRPRPSSRRRSRRSPRPSSSRRRPRRRSPPPPSSRRPPPSSPRPSSSPPSRSPRSSSSRSSSSPPPRPRRRRSRSRPSSPRRRPSRRPSPPSPSPSPPRSRSPRPSRPPPPPSSPPSPRRPSSSRPRRPPRRPPRRPSPSRRRPSPRRPRRPPPSSPSPSPSSRPSSPSRSPPPPRSRPRSRSRRRSRRPPSSPRPSRPSPSSSRPRPSSSRSRSSSSSSRSSSRRSPRSSPPPPSPPRRRPSPRSPSSRRPSSRRRSRRSPRSPRSPPRPSRSPSSRSSRRPSSRPRRRRPPRSPSSSPSPPPSPRPSRPPPSRRRPSSSPRRSSSPRRRSRSRSSRSRRPRSRPSPSRPPRRSRPRPSRPSRRPSSRPRRRPPPPSPRSRPSRRRPRRRSRRRPSSPRRRPSSRPRRSPPRRSSSPSSSSRSSSRSSSRRSSSRSSRPRSRRPRSSPSSRRPSPPRPRRRRSPSPRPPSRRPRPSRSSSSPRRRRRRPRSRPPRPSSSSPSRSSPPRSPRRPRRPRSSRRRRRSSSSSSPRSRSPRPSSRSRSRSSRSPSRPRRSSPRRSSSRRPRPSSPSRSPPRPRRRRSRRPPRSRRSRSSPPRSSPPSRRSRRSRRRSPSPPRRRPSSPSRSSRPPRPRSRSSSSPSRPPPPPRRSPSRPPRPRRRRSPPSPSRSSSRSSSSSSPPSPRSPRSSPPSPRSRPPSRPPPPRRSRSSSRRPSPSPSSRRPRPSRPRPSPSRSPRRPRPSSPRPPPRSRPRPPPRPRRSRPSRRSPRRRSSRPPSRPSSPPRRRRPSRPSRSPSRPPRPSPSRSPSPPRRSRSPRPPRRPPRRSPRSRPRPPPPRSSSSPPSSSSSRRPSRPPRPSRRPSSRSRRRSSRPRRPRSRRSPPSSSSRRRPSRSRRSSSPRSRRSSPSRPSPRRSPPPSPSPPPPPPPPRRSPPRPPSPPRPRSPRSSSPRSPSSSPSPRSRRRRSRPRRRSSRPSRSSRPRRRPSPSSSRRPRRRRSSRPPPSRPSRPSSPRSSRSRSPPRPRRSPRPSRSRSPRPSRPSRPPRSRPRPPRSSRSPRPSSSSPSRSPRPPPSPRRPRRSRPRRSRPSSPPSRRRRPRSSPPRPSRPSRRRSSPSSSSPRRPRPPSSPSPPPPPSPPPSSPSSPSPPSSPSPPPPRPRRPPSRPRRRPPRRSSSSSPPSSPRSPPRPPPSSPRSPRPPPPPRPRRRRSRPSRPRPRPSSPPPPPPRPSRPPSSSRSPRPPSRPPSPPPSRPSPSRSSPSRRPSPRRRSPSRSSRSPRSRRRRPSSRSRSRPSRPSSRRSPSRSSSRRRPPSPRSPPPPSRRRPRRRSRPRPRSSPPRRRSRPPPRRRRRPRRSSSRPPRPPRPPRRPRSSPRRRPRPRRRPRSPSRPRSSPPRSPPRSSRRSPSRPSSRRRSRPPSRSSPPSRSPRSPPPSPPSPPSRPSSRRSRPPPPPSSPSSSRPRPPSPSPSPPSPSSSRPSRPPRRPPPRPPRSPSSRPPRSPPPPSSPSPSRSPRRPRRPPPRRPSRPRRSSPPSPPPRRPRRSSPPPSRSSSRPPSSPPPRSPSSPPSPSRPRSSPSRRRPSRRPPRPRSPRSPSPRRRPPRPRPPPSPPRPRRPRPRRPSSSSSRRRSPPPSPRSPRSRRSRSSSSPSSPSSRPRRPRSSSSRRPPPPRPSRSSPSRSSRPPPRPRPRRRRPRSPRPPRSRPRPPPPRRRRPPSSSPSRRSRRRRRPSSPSPPRSSSRRPRPRSSRSRPPRPPPRSSRPRSSSPSPSSPSPRPPSRRRSPPPSPPPRRRSRRSSPSSSPPSPRPRRRPPPRPPSSPSSPSSPSRSPRPRPPSPSPRPPRPPRRSRPPSSPSSRSRRRPSSSSPSPSPSRPSPPSSRSRPPSSPSPRPRSRPPRSRRSRSSRPPRRSSRPRRPPSSRRRPRSPPRPRPRRPRPPPPPRSSPSSPPRRSRPRSRRSPRPRRRPPRPRPRRSPPSRPRSRRPPRSPPPRRPPSPPPRPSSPSSPPPSRPSPPSRRSRSPRSRSPSPSRSSPSSPPSPSPRSSSPRPPPRRRRRSRSPRPSPPRSRSRPPRSSPSRSRSPPRPPPSRRPSSSRSRSSRPRSSRPSRPSRPSRPSRRPSSPRSRRSRSSPRSPPPPPPSPRSRRSRPRPRRRRRSRRPRPRPPPSPRPPSSPSRPPPPSRPPSSSRSSPPSSRSRPPSRRSPRRRSSRPRRRRRSRPPPSRPPRRPSSRSPSSSRRSPRSRPSSSRSRRSRPRSRPSPRSPRRSPSRPSRPSSPSRSSPPPPSSPRRRPPRRPRRSRPRSSPRSPRPRPRPRPSSPRSRPSRSPPSPPPPRRRPPPSRPRPPRRPRSRSRPRSSRPRSRRPSSPPSPRRPPRRPSSRSRPRSRSSRSPSPRRSSPSRSPSPSPSRSRPSRSSRSPRRPPPSPRPRRSRPPSSPSRSPSPSSSRSSPRSRRRPRSRSRPSPPRPSSSPPRSPRSPSPSRPSPPRSPRPRRRRPRRSSRSRPSSPSSPSRSSRPPSSSSPPSPPSSSSRRPPSPPRPRSSPRPPSSSRPSSSPPRRPRPRSSSPSSRPSSRPSRPSRRRPSPRPSSRRRSSSPPRP'

bot = r.choice(list('RPS'))

_TEAM_NAME += '_' + bot

print _TEAM_NAME

rot = {\
        'R':{'R':'R', 'P':'P', 'S':'S'},\
        'P':{'R':'P', 'P':'S', 'S':'R'},\
        'S':{'R':'S', 'P':'R', 'S':'P'}}

'''
@description: Decides which move to make
@param history list<string> all the moves your opponent has made so far
@return string your move, 'R', 'P', or 'S'
'''
def strategy(history=None):
	
	
	
	# Extract moves from history
	if history is not None:
		history = [move.split(';')[1] for move in history]
		turn = len(history)
	else:
		turn = 0
		
	#YOUR CODE HERE#
	#
	throw = rot[bot][data[turn]]
	print turn, throw
	return throw.lower()

	# ... or just use a random strategy, if you're lame...

	#
	#END YOUR CODE#

################################################################################

# Initilize the connection
bot = BotHelper(_TEAM_NAME, strategy)

raw_input("Press the any key to finish. ")
